# Generated by Django 3.2.22 on 2023-11-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_staff_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_tutor',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
