# Generated by Django 3.2.22 on 2023-11-12 22:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_student_student_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='Student_tutor',
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('anumber', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('statement', models.TextField(blank=True, max_length=1000, null=True)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.staff')),
            ],
        ),
    ]
