# Generated by Django 3.2.22 on 2023-11-13 04:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20231113_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('cnumber', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('statement', models.TextField()),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='login.student')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_by', to='login.staff')),
            ],
        ),
    ]
