# Generated by Django 3.2.22 on 2023-12-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20231204_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.IntegerField(default=19600),
        ),
    ]
