# Generated by Django 3.2.22 on 2023-12-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_payslip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroutine',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='classroutine',
            name='end_time',
            field=models.TimeField(default='0:00'),
        ),
    ]
